vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /imglib
            upload_destination: '%kernel.project_dir%/public/imglib'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
