vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /imglib
            upload_destination: '%kernel.project_dir%/public/resources'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
