type OccurrenceSex = "male" | "female" | "Male" | "Female";

// Same order as /api docs
export interface Occurrence {
    id: number
    associatedCollectors: string[]
    associatedOccurrences: string[]
    associatedTaxa: string[]
    basisOfRecord: string
    behavior: string
    catalogNumber: string
    chronostratigraphyId: string[]
    collection: string
    collectionCode: string
    collectionIdentifier: string
    coordinatePrecision: string
    coordinateUncertaintyInMeters: number
    country: string
    county: string
    cultivationStatus: string
    dataGeneralizations: string
    datasetIdentifier: string
    dateIdentified: string
    day: number
    decimalLatitude: number
    decimalLongitude: number
    disposition: string
    duplicateId: string[]
    duplicateQuantity: number
    dynamicFields: object
    dynamicProperties: object
    endDayOfYear: number
    establishmentMeans: string
    eventDate: string
    eventIdentifier: string
    family: string
    fieldNotes: string
    fieldNumber: string
    footprintWkt: string
    genus: string
    geodeticDatum: string
    georeferencedBy: string
    georeferenceProtocol: string
    georeferenceRemarks: string
    georeferenceSources: string
    georeferenceVerificationStatus: string
    habitat: string
    identificationQualifier: string
    identificationReferences: string
    identificationRemarks: string
    identifiedBy: string
    individualCount: string
    informationWithheld: string
    infraspecificEpithet: string
    initialTimestamp: string
    institutionCode: string
    institutionIdentifier: string
    labelProject: number
    language: string
    latestDateCollected: string
    lifeStage: string
    locality: string
    localitySecurity: number
    localitySecurityReason: string
    locationIdentifier: string
    locationRemarks: string
    maximumDepthInMeters: number
    maximumElevationInMeters: number
    minimumDepthInMeters: number
    minimumElevationInMeters: number
    modifiedTimestamp: string
    month: number
    municipality: string
    observerUserId: string
    occurrenceIdentifier: string
    occurrenceRemarks: string
    otherCatalogNumbers: string
    ownerInstitutionCode: string
    preparations: string
    previousIdentifications: string
    processingStatus: string
    recordedBy: string
    recordEnteredBy: string
    recordNumber: string
    reproductiveCondition: string
    samplingEffort: string
    samplingProtocol: string
    scientificName: string
    scientificNameAuthorship: string
    scientificNameFull: string
    sex: OccurrenceSex
    sourcePrimaryKey: string
    specificEpithet: string
    startDayOfYear: number
    stateProvince: string
    storageLocation: string
    substrate: string
    taxon: string
    taxonRank: string
    taxonRemarks: string
    typeStatus: string
    verbatimAttributes: string
    verbatimCoordinates: string
    verbatimCoordinateSystem: string
    verbatimDepth: string
    verbatimElevation: string
    verbatimEventDate: string
    waterbody: string
    year: number
}
