enum OccurrenceSex {
    MALE,
    FEMALE
}

// Same order as /api docs
export interface Occurrence {
    id: number
    sourcePrimaryKey?: string
    basisOfRecord?: string
    occurrenceIdentifier?: string
    catalogNumber?: string
    otherCatalogNumbers?: string
    ownerInstitutionCode?: string
    institutionIdentifier?: string
    collectionIdentifier?: string
    datasetIdentifier?: string
    institutionCode?: string
    collectionCode?: string
    family?: string
    scientificNameFull?: string
    scientificName?: string
    genus?: string
    specificEpithet?: string
    taxonRank?: string
    infraspecificEpithet?: string
    scientificNameAuthorship?: string
    taxonRemarks?: string
    identifiedBy?: string
    dateIdentified?: string
    identificationReferences?: string
    identificationRemarks?: string
    identificationQualifier?: string
    typeStatus?: string
    recordedBy?: string
    recordNumber?: string
    associatedCollectors?: string[]
    eventDate?: Date
    latestDateCollected?: Date
    year?: number
    month?: number
    day?: number
    startDayOfYear?: number
    endDayOfYear?: number
    verbatimEventDate?: string
    habitat?: string
    substrate?: string
    fieldNotes?: string
    fieldNumber?: string
    eventIdentifier?: string
    occurrenceRemarks?: string
    informationWithheld?: string
    dataGeneralizations?: string
    associatedOccurrences?: string[]
    associatedTaxa?: string[]
    dynamicProperties?: object
    verbatimAttributes?: string
    behavior?: string
    reproductiveCondition?: string
    cultivationStatus?: string
    establishmentMeans?: string
    lifeStage?: string
    sex?: OccurrenceSex
    individualCount?: string
    samplingProtocol?: string
    samplingEffort?: string
    preparations?: string
    locationIdentifier?: string
    waterbody?: string
    country?: string
    stateProvince?: string
    county?: string
    municipality?: string
    locality?: string
    localitySecurity?: number
    localitySecurityReason?: string
    decimalLatitude?: number
    decimalLongitude?: number
    geodeticDatum?: string
    coordinateUncertaintyInMeters?: number
    footprintWkt?: string
    coordinatePrecision?: string
    locationRemarks?: string
    verbatimCoordinates?: string
    verbatimCoordinateSystem?: string
    georeferencedBy?: string
    georeferenceProtocol?: string
    georeferenceSources?: string
    georeferenceVerificationStatus?: string
    georeferenceRemarks?: string
    minimumElevationInMeters?: number
    maximumElevationInMeters?: number
    verbatimElevation?: string
    minimumDepthInMeters?: number
    maximumDepthInMeters?: number
    verbatimDepth?: string
    previousIdentifications?: string
    disposition?: string
    storageLocation?: string
    language?: string
    processingStatus?: string
    recordEnteredBy?: string
    duplicateQuantity?: number
    labelProject?: number
    dynamicFields?: object
    initialTimestamp?: Date
    modifiedTimestamp?: Date
    taxaId?: string
    observerUserId?: string
    collectionId?: number
    duplicateId?: string[]
    chronostratigraphyId?: string[]
}