<?php

namespace App\Repositories;

use App\Entities\User;
use Doctrine\ORM\EntityRepository;
use EntityManager;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllUsers()
    {
        return EntityManager::createQueryBuilder()
            ->select('u.id', 'u.name', 'u.email', 'u.password')
            ->from(User::class, 'u')
            ->orderBy('u.name', 'ASC')
            ->getQuery()
            ->getResult();
        ;

    }

}